version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/ojs-chi"
      - "/ojs-chi/examples"
      - "/ojs-echo"
      - "/ojs-echo/examples"
      - "/ojs-fiber"
      - "/ojs-fiber/examples"
      - "/ojs-gin"
      - "/ojs-gin/examples"
      - "/ojs-gorm"
      - "/ojs-gorm/examples"
      - "/ojs-serverless"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
    commit-message:
      prefix: "chore(ci):"
